### ISSUE TITLE
WD201 Milestones

### ISSUE THREAD

**Issue by cp-Coder** [cp-Coder/WD201-Milestones#1]
# Updates

- [ ] Level 1 - Introduction to Node.js
- [ ] Level 2 - Working with NPM
- [ ] Level 3 - Node.js deep dive
- [ ] Level 4 - Testing
- [ ] Level 5 - Databases and Sequelize
- [ ] Level 6 - Backend Web development with Express.js
- [ ] Level 7 - Add User Interface for To-do Application
- [ ] Level 8 - EJS Templating
- [ ] Level 9 - HTML forms to save and accept user inputs
- [ ] Level 10 - User Authentication and final wrap-up
